'use client';
import {ResumenSala,Elegidos} from '../../../lib/dashboard';
import {generarClaseLocal} from '../../../lib/generador.mjs';
import {MoodBrand} from '../../../lib/brand';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {sb} from '../../../lib/supabase';
import {resumir,promptParaGenerar} from '../../../lib/clase.mjs';
import {FUENTES} from '../../../lib/gamma.mjs';

function Exercise({e,index,reserve}){return <article className="exercise"><div className="eyebrow">{reserve?'Por si queda tiempo':'Ejercicio '+(index+1)+' · 9 min + 3 min de demo'}</div><h3>{e.titulo}</h3><span className="tag">{e.capacidad}</span><p>{e.aQuienSirve}</p><div className="reason"><strong>Por qué lo elegimos</strong><p>{e.motivo}</p><small>{e.casos.length} casos representados</small></div><details><summary>Ver práctica y solución</summary><h4>Datos ficticios para practicar</h4><pre>{e.datos}</pre><ol>{e.pasos.map((p,i)=><li key={i}>{p}</li>)}</ol><h4>Prompt del ejercicio</h4><pre>{e.prompt}</pre><h4>El loop: mejora en dos turnos</h4>{e.loops.map((p,i)=><div key={i}><strong>Turno {i+1}</strong><pre>{p}</pre></div>)}{e.reto&&<><h4>Reto opcional</h4><pre>{e.reto}</pre></>}<h4>Resultado del ejemplo</h4><p>{e.resultado}</p><h4>Cómo comprobarlo</h4><p>{e.verificacion}</p><h4>Para mañana</h4><p>{e.adaptacion}</p><h4>El combo · demo de 3 minutos</h4><p>{e.combo.frase}</p><p>{e.combo.cadena.join(" → ")}</p><span className="tag">{e.combo.estado}</span><p>Plan: {e.combo.plan}</p><p>{e.combo.limitacion}</p><h4>Preparación y pasos para casa</h4><ol>{e.combo.pasos.map((p,i)=><li key={i}>{p}</li>)}</ol>{e.combo.fuentes.map(f=><p key={f}><a className="text-link" href={FUENTES[f]} target="_blank" rel="noreferrer">Documentación: {f} ↗</a></p>)}</details></article>}
const CAMPOS_ABIERTOS={destino:'Resultado esperado',origen:'Origen de la tarea',superpoder:'Superpoder',freno:'Freno',herramienta:'Herramienta',dispositivo:'Dispositivo',nivel:'Relación con la IA'};
function Agrupaciones({r,proyectar}){const [campo,setCampo]=useState('destino');const grupos=(r.agrupaciones||[]).filter(g=>g.campo===campo);return <section className="panel"><div className="section-head"><div><span className="eyebrow">DE LAS RESPUESTAS A LOS EJERCICIOS</span><h2>Originales y equivalencias</h2></div><label>Ver pregunta<select className="campo" value={campo} onChange={e=>setCampo(e.target.value)}>{Object.entries(CAMPOS_ABIERTOS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><p className="tenue">Conservamos cada texto original. Unificamos equivalencias claras por formato y objetivo; las respuestas ambiguas quedan pendientes. Para elegir ejercicios, reunimos el mismo resultado y capacidad aunque cambie el origen.</p><p>{r.normalizacion?.pendientes.length||0} respuestas pendientes de revisar. No se asignan automáticamente a otra categoría.</p><div className="grid-two">{grupos.map((g,i)=><article className="task" key={i}><span className="tag">{g.n} {g.n===1?'respuesta':'respuestas'} · {g.revisar?'Revisar':'Agrupada'}</span><h3>{g.revisar&&proyectar?'Respuesta abierta por revisar':g.grupo}</h3>{!proyectar&&<details><summary>Ver {g.variantes.length} formas de responder</summary><ul>{g.variantes.map((v,j)=><li key={j}>“{v.texto}” · {v.n}</li>)}</ul></details>}</article>)}</div>{!grupos.length&&<p className="empty">Aún no hay respuestas para esta pregunta.</p>}</section>}
export default function Host({params}){
 const codigo=params.codigo;
 const [pin,setPin]=useState(''),[autorizado,setAutorizado]=useState(false),[datos,setDatos]=useState(null),[clase,setClase]=useState(null),[prompt,setPrompt]=useState(''),[ocupado,setOcupado]=useState(false),[aviso,setAviso]=useState(''),[conexion,setConexion]=useState(true),[filtro,setFiltro]=useState(''),[proyectar,setProyectar]=useState(false),[accediendo,setAccediendo]=useState(false);
 const storage='clase-v4:'+codigo;
 const traer=useCallback(async(p)=>{const {data,error}=await sb.rpc('resumen_sala',{p_codigo:codigo,p_pin:p});if(error||!data)throw Error('No se pudo acceder a la sala. Revisa tu PIN y conexión.');return data},[codigo]);
 async function probar(p){setAccediendo(true);try{const d=await traer(p);setDatos(d);setAutorizado(true);sessionStorage.setItem('host:'+codigo,p);setAviso('')}catch(e){setAviso(e.message)}finally{setAccediendo(false)}}
 useEffect(()=>{const p=sessionStorage.getItem('host:'+codigo);if(p) {setPin(p);probar(p)}try{const saved=JSON.parse(localStorage.getItem(storage));if(saved?.version===4){setClase(saved);setPrompt(saved.prompt)}}catch{}},[codigo]);
 useEffect(()=>{if(!autorizado)return;let live=true;async function poll(){try{const d=await traer(pin);if(live){setDatos(d);setConexion(true)}}catch{if(live)setConexion(false)}}const t=setInterval(poll,5000);return()=>{live=false;clearInterval(t)}},[autorizado,traer,pin]);
 const r=useMemo(()=>resumir(datos),[datos]);
 const tareas=r.tareas.filter(t=>(t.oficio+' '+t.tarea+' '+t.resultado+' '+Object.values(t.originales||{}).join(' ')).toLowerCase().includes(filtro.toLowerCase()));
 const updated=Boolean(clase&&JSON.stringify(clase.resumen)!==JSON.stringify(r));
 const previa=useMemo(()=>generarClaseLocal(r),[r]);
 const elegida=clase&&!updated?clase:previa;
 async function copy(t,msg){try{await navigator.clipboard.writeText(t);setAviso(msg)}catch{setAviso('No se pudo copiar. Selecciona el texto o descarga el archivo.')}}
 function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([prompt],{type:'text/markdown;charset=utf-8'}));a.download='clase-'+codigo+'-gamma.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 async function generar(){setOcupado(true);setAviso('');try{const response=await fetch('/api/generar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({codigo,pin})});const j=await response.json();if(!response.ok)throw Error(j.error);const c={version:4,...j};setClase(c);setPrompt(c.prompt);try{localStorage.setItem(storage,JSON.stringify(c))}catch{}setAviso(j.aviso||'Clase generada. Revisa los ejercicios y copia el documento en Gamma.')}catch(e){setAviso(e.message)}finally{setOcupado(false)}}
 async function publicar(){if(!clase)return;setOcupado(true);try{const {error}=await sb.rpc('publicar_ejercicios',{p_codigo:codigo,p_pin:pin,p_ejercicios:clase.ejercicios.map(e=>({...e,prompt:e.prompt+'\n\nDATOS FICTICIOS PARA PRACTICAR:\n'+e.datos,pasos:[...e.pasos,...e.loops.map((p,i)=>'Loop '+(i+1)+': '+p),...(e.reto?['Reto opcional: '+e.reto]:[]),'Comprobación: '+e.verificacion,'Resultado de referencia: '+e.resultado,'Para mañana: '+e.adaptacion]}))});if(error)throw error;setDatos(await traer(pin));setAviso('Los tres ejercicios principales ya están disponibles en los teléfonos.')}catch{setAviso('No se pudieron publicar los ejercicios. Intenta nuevamente.')}finally{setOcupado(false)}}
 async function cambiar(){setOcupado(true);try{const state=datos?.sesion?.estado==='cerrada'?'recibiendo':'cerrada';const {error}=await sb.rpc('cambiar_estado',{p_codigo:codigo,p_pin:pin,p_estado:state});if(error)throw error;setDatos(await traer(pin));setAviso(state==='cerrada'?'Sala cerrada a nuevos ingresos.':'Sala abierta.')}catch{setAviso('No se pudo cambiar el estado de la sala.')}finally{setOcupado(false)}}
 async function guardar(){setOcupado(true);try{const saved={...clase,prompt,version:4};const {error}=await sb.rpc('guardar_prompt',{p_codigo:codigo,p_pin:pin,p_prompt:JSON.stringify(saved)});if(error)throw error;localStorage.setItem(storage,JSON.stringify(saved));setClase(saved);setAviso('Versión guardada. Las nuevas respuestas no modifican este prompt.')}catch{setAviso('No se pudo guardar. Descarga el prompt para conservarlo.')}finally{setOcupado(false)}}
 if(!autorizado)return <main className="movil login"><MoodBrand/><div className="entry-card"><span className="eyebrow">Espacio de facilitación</span><h1>Tu sala.<br/>Tu próxima clase.</h1><p className="tenue">Revisa las respuestas y transforma las necesidades del grupo en ejercicios prácticos.</p><label htmlFor="pin">PIN de facilitadora</label><input id="pin" className="campo" type="password" autoComplete="off" placeholder="Ingresa tu PIN" value={pin} onChange={e=>setPin(e.target.value)} onKeyDown={e=>e.key==='Enter'&&probar(pin)}/><button className="btn" disabled={accediendo||!pin.trim()} onClick={()=>probar(pin)}>{accediendo?'Abriendo…':'Abrir dashboard →'}</button>{aviso&&<p role="alert" className="notice">{aviso}</p>}</div></main>;
 return <main className={'compact-dashboard '+(proyectar?'compact-projection':'')}>
 <header className="compact-header"><MoodBrand/><div><span className={'live '+(!conexion?'offline':'')}>{conexion?'En vivo':'Sin conexión · última lectura'}</span><button className="btn fantasma" onClick={()=>setProyectar(!proyectar)}>{proyectar?'Salir de proyección':'Proyectar'}</button></div></header>
 <div className="compact-heading"><div><span className="eyebrow">TRABAJA MEJOR, NO MÁS</span><h1>Esta es la clase que eligieron.</h1></div><small>Sala {codigo} · 60 minutos + preguntas</small></div>
 {aviso&&<div role="status" className="notice">{aviso}<button aria-label="Cerrar aviso" onClick={()=>setAviso('')}>×</button></div>}
 <ResumenSala r={r}/><Elegidos r={r} ejercicios={elegida.ejercicios}/>
 {!proyectar&&<section className="compact-gamma"><div><span className="eyebrow">DE LOS RESULTADOS A LA PRESENTACIÓN</span><h2>Tu documento para Gamma</h2><p>{updated?'Llegaron nuevas respuestas. Actualiza el documento para incluirlas.':clase?'Listo: teoría, consenso, ejercicios, prompts y soluciones.':'Genera las 26 tarjetas con las prioridades y ejercicios de esta sala.'}</p></div><div className="compact-gamma-actions"><button className="btn" onClick={generar} disabled={ocupado||!r.tareas.length}>{ocupado?'Generando…':clase?'Actualizar documento':'Generar documento'}</button><button className="btn fantasma" disabled={!prompt||updated||ocupado} onClick={()=>copy(prompt,'Documento copiado. Pégalo en Gamma.')}>Copiar para Gamma</button><a href="https://gamma.app/" target="_blank" rel="noreferrer">Abrir Gamma ↗</a></div>
 {prompt&&<details className="compact-details"><summary>Ver o editar el documento completo</summary><textarea className="gamma-editor" aria-label="Documento editable para Gamma" value={prompt} onChange={e=>setPrompt(e.target.value)}/><div className="actions"><button className="btn fantasma" onClick={download}>Descargar .md</button><button className="btn fantasma" disabled={ocupado} onClick={guardar}>Guardar edición</button></div><p className="tenue">Editar el documento no cambia los ejercicios publicados en los teléfonos.</p></details>}
 </section>}
 {!proyectar&&<details className="compact-details compact-support"><summary>Ver respuestas originales y materiales de apoyo</summary><Agrupaciones r={r} proyectar={false}/><label>Buscar tareas<input className="campo search" placeholder="Buscar una tarea…" value={filtro} onChange={e=>setFiltro(e.target.value)}/></label><div className="task-grid">{tareas.map(t=><article className="task" key={t.id}><h3>{t.tarea}</h3><p>{t.originales?.origen||t.origen||'Origen pendiente'} → {t.originales?.destino||t.destino||'Destino pendiente'}</p></article>)}</div><h2>Prácticas y demostraciones</h2><div className="grid-two">{elegida.ejercicios.map((e,i)=><Exercise key={i} e={e} index={i}/>)}</div><div className="actions"><button className="btn fantasma" disabled={!clase||updated||ocupado} onClick={publicar}>Publicar ejercicios en los teléfonos</button><button className="btn fantasma" disabled={!r.tareas.length} onClick={()=>copy(promptParaGenerar(r),'Prompt maestro con las respuestas copiado.')}>Copiar prompt maestro</button><button className="text-button" disabled={ocupado} onClick={cambiar}>{datos?.sesion?.estado==='cerrada'?'Reabrir sala':'Cerrar nuevos ingresos'}</button></div></details>}
 <footer className="compact-footnote"><span>* Tiempo dedicado a tareas repetitivas; no es ahorro garantizado.</span><span>{r.normalizacion?.pendientes.length||0} respuestas por revisar · Agrupación por equivalencias</span></footer>
 </main>;
}
