// Contenido común y contrato de salida: la IA personaliza los ejercicios, no inventa funciones.
export const FUNCIONES=['Proyecto','Gem','GPT','NotebookLM','Skill','MCP','Tarea programada','Artefacto','Canvas'];
export const FUENTES={
 skills:'https://support.claude.com/en/articles/12512180-use-skills-in-claude',
 gems:'https://support.google.com/gemini/answer/15235603',
 notebook:'https://support.google.com/gemininotebook/answer/16213268',
 tareas:'https://help.openai.com/en/articles/10291617-scheduled-tasks-in-chatgpt'
};
export const TECNICAS=['entrevista','critica','alternativas'];
export const REGLAS_NUEVAS=`
AMPLIACIÓN DEL TALLER: 15 minutos de fundamentos, 5 de lectura de sala, 36 de ejercicios (9 práctica + 3 demo cada uno), 4 de cierre. Preguntas después. El documento tendrá 26 tarjetas breves: portada, diez de fundamentos, cuatro de sala, nueve de ejercicios, mapa y cierre. No fuerces la teoría dentro de las 15 tarjetas anteriores.
El JSON conserva el contrato anterior y AÑADE:
- frenoEjercicio: índice 1, 2 o 3 del ejercicio que enseña a superar el freno dominante; frenoRespuesta: explicación honesta de máximo 18 palabras. Si no hay freno declarado, enseña verificación y dilo.
- Cada ejercicio: origenCaso (ID de UNA confesión entre sus casos; vacío si complementario), origenResumen (máximo 9 palabras, paráfrasis sin nombres que identifique la tarea y el oficio sin exponer información privada), tecnica (respectivamente entrevista, critica, alternativas), loops (exactamente DOS prompts completos), reto (prompt avanzado opcional, string vacío si no corresponde), combo.
- combo: {frase: máximo 17 palabras, cadena: tres textos de máximo 3 palabras cada uno, plan: máximo 7 palabras, protagonistas: nombres de FUNCIONES, apoyos: nombres de FUNCIONES, pasos: 3 a 5 instrucciones detalladas para replicar en casa, estado: "Manual" o "Preparación previa", limitacion: requisitos y traspasos manuales, fuentes: claves de FUENTES utilizadas}.
FUNCIONES: Proyecto, Gem, GPT, NotebookLM, Skill, MCP, Tarea programada, Artefacto, Canvas.
Cada función es protagonista como máximo en UN ejercicio. Puede ser apoyo en otro. No obligues a cubrirlas todas. Los tres eslabones deben pasarse información: contexto, procedimiento y resultado. Un paso puede ser manual; nómbralo. No simules una automatización funcionando. La demo de 3 minutos comienza con la configuración ya preparada; los pasos para casa incluyen esa preparación. Si no puedes justificar un combo, usa contexto guardado → prompt manual → salida de texto y deja funciones fuera. Los títulos de etapas no son una conexión automática entre productos.
FUENTES verificadas: skills=${FUENTES.skills}; gems=${FUENTES.gems}; notebook=${FUENTES.notebook}; tareas=${FUENTES.tareas}.
CAPACIDADES: Skills de Claude son procedimientos con instrucciones y posibles recursos/código; requieren ejecución de código habilitada, disponibles en Free/Pro/Max según límites y políticas. Un skill no programa su propia ejecución. Gem guarda instrucciones y contexto; se crea y prueba en Gemini web. NotebookLM (la documentación actual lo llama Gemini Notebook) trabaja con fuentes y permite resúmenes en audio, con límites gratuitos. Las tareas de ChatGPT admiten ejecuciones futuras y algunas apps compatibles según cuenta/permisos; NO funcionan con GPTs ni acceden a archivos de un proyecto. MCP es un protocolo de conexión, no un temporizador: un conector debe exponer explícitamente la acción de lectura/escritura y autorizarse. No prometas WhatsApp directo, modificar un Sheet por tener Drive, ni actualizar un artefacto desde una tarea. No inventes planes: si no hay evidencia suficiente escribe "Disponibilidad por confirmar en la cuenta" y marca preparación previa. No afirmes que una función sin fuente del catálogo fue verificada.
DISEÑO: Prompt base con etiquetas Rol, Contexto, Tarea, Formato. Usa [CORCHETES EN MAYÚSCULAS] con explicación de qué poner; permite practicar con los datos ficticios incluidos sin tener que inventar información. Nunca ordenes ejecutar pagos, enviar mensajes ni cambiar una agenda real. En ejercicio 1, el prompt base pide únicamente preguntas aclaratorias; loop1 aporta respuestas de ejemplo y pide primer resultado; loop2 ajusta a la necesidad. Ejercicio2: loop1 contrasta y critica contra fuente, loop2 entrega corrección. Ejercicio3: loop1 pide tres versiones, loop2 selecciona una con criterios concretos. Pedir autocrítica no equivale a verificar hechos: incorpora cotejo con la fuente. Cada loop debe sonar a SU caso. El freno principal se trabaja dentro del ejercicio indicado, no solo en el título.
NIVEL: si domina debutante, pedido breve y resultado útil inmediato. Si domina uso diario, reto más ambicioso; si sala dividida, versión base y reto. Usa la herramienta mayoritaria para texto y menciona que la misma práctica se puede pegar en las otras. El oficio nunca sustituye evidencia ni demuestra habilidades.
LÍMITES DE TEXTO: titulo máximo 7 palabras; aQuienSirve 8; resultado 14; verificacion 10; adaptacion 8; cierre 12. Mantén datos de ejemplo pequeños pero suficientes y solución comprobable. Prompts, loops y pasos detallados no tienen el límite de 40 palabras; los pasos viven en los materiales para casa, no en diapositivas.
CONTROL: antes de entregar revisa fidelidad de casos/cifras/anonimato, capacidades y loops diferentes, utilidad y traspasos reales de combos, planes honestos, base móvil gratuita y estructura JSON. Corrige inconsistencias; si una idea no funciona después de tres revisiones, cambia el combo, nunca el patrón seleccionado. Esta revisión es editorial, no una prueba real de ejecución. Devuelve solo JSON, sin describir revisiones.`;
export function palabras(text){return (String(text).match(/[\p{L}\p{N}]+(?:[’'–-][\p{L}\p{N}]+)*/gu)||[]).length}
const breve=(s,n)=>String(s||'').split(/\s+/).slice(0,n).join(' ');
function linea(text){return String(text||'').replace(/[\r\n]+/g,' ').replace(/[<>#|`]/g,'').trim()}
function bloque(text){const runs=String(text).match(/`+/g)||[];const f='`'.repeat(Math.max(3,...runs.map(x=>x.length+1)));return f+'text\n'+text+'\n'+f}
export function validarAmpliacion(c,r){
 const fail=m=>{throw Error(m+' Intenta generar nuevamente.')};
 if(!Number.isInteger(c.frenoEjercicio)||c.frenoEjercicio<1||c.frenoEjercicio>3||!c.frenoRespuesta||palabras(c.frenoRespuesta)>18)fail('Falta la respuesta concreta al freno.');
 const usados=new Set();
 c.ejercicios.forEach((e,i)=>{
  if(e.tecnica!==TECNICAS[i]||!Array.isArray(e.loops)||e.loops.length!==2||e.loops.some(x=>typeof x!=='string'||!x.trim()))fail('Los loops están incompletos.');
  if(typeof e.reto!=='string'||typeof e.origenResumen!=='string'||!e.origenResumen.trim())fail('Falta el origen o adaptación del ejercicio.');
  if(e.patron==='complementario'?e.origenCaso!=='':!e.casos.includes(e.origenCaso))fail('No se puede rastrear la confesión de origen.');
  for(const [k,n] of Object.entries({titulo:7,aQuienSirve:8,origenResumen:9,resultado:14,verificacion:10,adaptacion:8}))if(palabras(e[k])>n)fail('El texto del ejercicio es demasiado extenso.');
  const b=e.combo;
  if(!b||!b.frase||palabras(b.frase)>17||!b.plan||palabras(b.plan)>7||!Array.isArray(b.cadena)||b.cadena.length!==3||b.cadena.some(x=>typeof x!=='string'||!x.trim()||palabras(x)>3)||!['Manual','Preparación previa'].includes(b.estado)||!b.limitacion||!Array.isArray(b.pasos)||b.pasos.length<3||b.pasos.length>5||b.pasos.some(x=>typeof x!=='string'||!x.trim()))fail('La demostración necesita una cadena y preparación concretas.');
  if(!Array.isArray(b.protagonistas)||!Array.isArray(b.apoyos)||!Array.isArray(b.fuentes)||b.fuentes.some(x=>!FUENTES[x]))fail('Faltan referencias válidas para la demostración.');
  for(const f of [...b.protagonistas,...b.apoyos])if(!FUNCIONES.includes(f))fail('La demostración usa una función desconocida.');
  for(const f of b.protagonistas){if(usados.has(f)||b.apoyos.includes(f))fail('Una función se repite como protagonista.');usados.add(f)}
 });
 if(palabras(c.cierre)>12)fail('El cierre es demasiado extenso.');
 return c;
}
export function tarjetasGamma(c,r){
 const cards=[];const add=(titulo,texto,extras='')=>{if(palabras(texto)>40)throw Error('La tarjeta «'+titulo+'» excede 40 palabras. Intenta generar nuevamente.');cards.push('# '+linea(titulo)+'\n\n'+texto+(extras?'\n\n'+extras:''))};
 add('Trabaja mejor, no más','Social Club · Gran Ciudad Nuevo Polanco · CDMX\n23 de septiembre de 2026\nCon Liliana Ferro, ingeniera de sistemas y consultora de IA.\n60 minutos + preguntas.');
 add('¿Qué es la IA?','Tecnología que aprende patrones de datos para reconocer, predecir o generar resultados. Hoy usaremos IA generativa: produce texto y otros contenidos a partir de nuestras instrucciones. Tú defines el objetivo y revisas el resultado.');
 add('¿Qué no es?','No es una persona ni una fuente infalible. Puede responder con seguridad y equivocarse. Tampoco conoce automáticamente tu negocio, lee tu WhatsApp o modifica tu agenda: necesita contexto, herramientas y permisos.');
 add('Un prompt es un encargo','Rol: desde qué perspectiva ayudar. Contexto: qué ocurre. Tarea: qué debe hacer. Formato: cómo entregarlo. Este encargo nace de una necesidad de la sala.',bloque(c.ejercicios[0].prompt));
 add('Del primer intento al loop','Un loop es conversar, revisar y ajustar. Aclara lo que falta, compara con la fuente y pide una mejora concreta. Suele mejorar el encargo porque aporta información y criterios; repetir la pregunta no garantiza calidad.',bloque('Antes de responder, hazme dos preguntas sobre lo que falta.\nDespués, señala qué parte de la respuesta debo verificar con mi información original.'));
 add('Contexto que no repites','Proyecto: carpeta de conversaciones, instrucciones y materiales. Gem de Gemini y GPT personalizado: asistentes con instrucciones guardadas. No son lo mismo que entrenar un modelo nuevo. Su disponibilidad y creación dependen de la cuenta.');
 add('Un skill es una receta reutilizable','Un skill reúne instrucciones y recursos para repetir un procedimiento. Ejemplo: leer pedidos, detectar datos faltantes y devolver siempre las mismas columnas. No es solo un prompt largo ni un reloj que lo ejecuta solo.');
 add('MCP: el puente hacia otras herramientas','MCP es un protocolo para conectar la IA con herramientas y datos. Como un adaptador: cada conexión ofrece acciones específicas y pide permisos. Poder leer correos no significa poder enviar mensajes o modificar cualquier hoja.');
 add('Artefactos y canvas: trabajar sobre el resultado','Un artefacto de Claude puede presentar un documento o una herramienta interactiva. Un canvas permite editar y revisar contenido en un espacio de trabajo. Ejemplo: convertir un borrador en una plantilla reutilizable. No implican publicación automática.');
 add('Una tarea programada tiene un cuándo','Pide una ejecución futura o periódica. Ejemplo: un recordatorio para revisar pendientes. Conectar correo y escribir en una hoja requiere además acciones compatibles y permisos. Una programación no vuelve compatibles herramientas que no lo son.');
 add('NotebookLM: conversar con tus fuentes','Reúne materiales para preguntar, contrastar referencias y preparar resúmenes, incluso audio. Ejemplo: estudiar tres documentos antes de una reunión. Comprueba las citas. Google también lo documenta como Gemini Notebook; funciones y límites dependen de la cuenta.');
 const nivel=breve(r.niveles[0]?.k||'Sin respuestas',9), herramienta=breve(r.herramientas[0]?.k||'Sin respuesta',5);
 add('Así llegó esta sala',`${r.personas} registros · ${r.completas} encuestas completas.\nNivel más declarado: ${linea(nivel)}.\nHerramienta más elegida: ${linea(herramienta)}.\nAquí nadie presenta examen: trabajamos desde donde estamos.`);
 add('El tiempo que queremos recuperar',`${r.horas.texto}, según ${r.horas.n} respuestas. Son intervalos de tiempo declarado, no ahorro garantizado.\n${linea(c.cierre)}`);
 const nombres=['Escribir','Leer','Ordenar','Analizar','Responder','Crear'];
 add('Ustedes votaron la clase',r.votos.slice(0,6).map(v=>`${nombres[['Escribir más rápido, con mi estilo','Leer lo largo y encontrar lo importante','Poner orden en mi agenda y pendientes','Sacar conclusiones de mis números','Preparar mis respuestas de siempre','Crear presentaciones, imágenes o contenido'].indexOf(v.k)]||'Otro'}: ${v.n}`).join(' · ')+`\nHoy: ${c.ejercicios.map(e=>linea(e.capacidad)).join(' → ')}.\n${r.seleccion.patrones.length<3?'Muestra parcial: incluye prácticas complementarias.':r.seleccion.coincidencias<2?'No hay tres capacidades que cubran dos prioridades del podio.':'Tres capacidades distintas, elegidas por cobertura y votos.'}`);
 add('El freno tiene respuesta',`${linea(breve(r.frenos[0]?.k||'Sin freno declarado',10))}.\n${linea(c.frenoRespuesta)}\nLo practicamos en el ejercicio ${c.frenoEjercicio}.`);
 c.ejercicios.forEach((e,i)=>{
  add(`${i+1}. Hazlo tú: ${e.titulo}`,`${e.patron==='complementario'?'Práctica complementaria':'Nace de'}: ${linea(e.origenResumen)}.\nPara: ${linea(e.aQuienSirve)}.\n9 minutos, texto y cuenta gratuita. Usa el ejemplo ficticio o sustituye los corchetes.`,bloque(e.prompt+'\n\nDATOS FICTICIOS PARA PRACTICAR:\n'+e.datos));
  add(`${i+1}. Prueba, revisa y mejora`,`Resultado del ejemplo: ${linea(e.resultado)}\nComprueba: ${linea(e.verificacion)}\nMañana: ${linea(e.adaptacion)}`,bloque(e.loops[0])+'\n\n'+bloque(e.loops[1])+(e.reto?'\n\nReto opcional:\n\n'+bloque(e.reto):''));
  const b=e.combo;add(`${i+1}. El combo de Liliana`,`${linea(b.frase)}\n${b.cadena.map(linea).join(' → ')}\nPlan: ${linea(b.plan)}.\nDemo: 3 minutos. ${b.estado}.`);
 });
 add('El mapa de hoy','●: protagonista · ◦: apoyo · —: no utilizado hoy.\n\n| Función | 1 | 2 | 3 |\n|---|---|---|---|\n'+FUNCIONES.map(f=>'| '+f+' | '+c.ejercicios.map(e=>e.combo.protagonistas.includes(f)?'●':e.combo.apoyos.includes(f)?'◦':'—').join(' | ')+' |').join('\n'));
 add('Desde mañana','Empieza con una tarea pequeña.\nComprueba el resultado con su fuente.\nGuarda el prompt que funcionó.\n'+r.horas.texto+' declaradas: ahora elige dónde empezar.\n'+linea(c.cierre));
 return cards;
}
export function documentoGamma(c,r){return tarjetasGamma(c,r).join('\n\n---\n\n')}
export function promptManual(r,instruccion){return `Eres diseñadora instruccional. Genera el DOCUMENTO FINAL para Gamma, no JSON. Las reglas siguientes describen los campos que debes desarrollar, pero tu entrega debe ser exclusivamente Markdown con 26 tarjetas, cada una iniciada por # y separada por una línea ---. Sin comentarios antes ni después.\n${instruccion}\nEXCEPCIÓN DE FORMATO FINAL: no entregues JSON. Distribución exacta: 1 portada; 2 qué es IA; 3 qué no es; 4 anatomía de prompt con caso real; 5 loop y por qué ayuda; 6 Proyecto/Gem/GPT; 7 skill con ejemplo; 8 MCP con ejemplo y permisos; 9 artefacto/canvas; 10 tarea programada; 11 NotebookLM; 12 sala; 13 horas y deseos autorizados sin nombres; 14 votos y ejercicios; 15 freno; 16–24 tres tarjetas por ejercicio (Hazlo tú con datos ficticios, loop y comprobación, combo); 25 mapa de funciones con P/A/—; 26 cierre. Máximo 40 palabras por tarjeta sin contar bloques de prompts. Prompts y loops completos en bloques de código. Los pasos extensos de configuración son material para casa, no prometas ejecutarlos en tres minutos. No inventes respuestas.\n<respuestas>\n${JSON.stringify(r,null,2)}\n</respuestas>`}
