'use client';
import {useState,useEffect} from 'react';
import {casosPublicos,RESPUESTAS_FRENO} from './clase.mjs';
const TITULOS=['El termómetro','Con qué practicamos','El tiempo y los sueños','Las confesiones','El mapa del trabajo','Nuestros superpoderes','Lo que nos frena'];
function Ranking({items,total}){return <div className="barras">{items.map((x,i)=><div className="barra" key={x.k}><div className="bar-label"><span>{i+1}. {x.k}</span><strong>{x.n} <small>de {total}</small></strong></div><div className="pista"><div className="llena" style={{width:100*x.n/Math.max(total,1)+'%'}}/></div></div>)}{!items.length&&<p className="empty">La primera respuesta abre esta historia.</p>}</div>}
function Horas({h}){const [f,setF]=useState(1);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame,start;function tick(t){start??=t;const n=Math.min(1,(t-start)/700);setF(n);if(n<1)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[h.min,h.max,h.n]);return <div className="hours-number" aria-label={h.texto}><span aria-hidden="true">{!h.n?h.texto:h.max===null?`Más de ${Math.round(h.min*f)} h/semana`:`${Math.round(h.min*f)}–${Math.round(h.max*f)} h/semana`}</span></div>}
export default function Story({r,datos,onGenerar,ocupado}){
 const [slide,setSlide]=useState(0),publicos=casosPublicos(datos),suenos=publicos.filter(p=>p.sueno);
 const words=new Map();const stop=new Set('para como esta este esas esos unas unos unas tengo quiero tener usaría tiempo horas parte más mis los las con por que del una unos sería poder'.split(' '));for(const p of suenos)for(const w of new Set(p.sueno.toLocaleLowerCase('es').match(/[a-záéíóúüñ]{4,}/gi)||[]))if(!stop.has(w))words.set(w,(words.get(w)||0)+1);const nube=[...words].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,25);
 const nivelOrden=['Ni nos conocemos','Salimos una vez y no hubo química','Nos vemos de vez en cuando','Es mi compañera de trabajo diaria'];
 const freno=r.frenos[0],empates=r.frenos.filter(x=>x.n===freno?.n);
 return <section className="story"><nav className="story-tabs" aria-label="Historia de la sala">{TITULOS.map((t,i)=><button key={t} onClick={()=>setSlide(i)} aria-current={slide===i?'step':undefined}>{i+1}. {t}</button>)}</nav><div className="story-stage panel"><div className="eyebrow">LA SALA SE VE A SÍ MISMA · {slide+1} / 7</div><h2>{TITULOS[slide]}</h2>
 {slide===0&&<><p>Así está nuestra relación con la IA. Sin juicio: frecuencia no significa dominio.</p><Ranking items={nivelOrden.map(k=>({k,n:r.niveles.find(v=>v.k===k)?.n||0}))} total={r.niveles.reduce((n,x)=>n+x.n,0)}/><div className="thermometer">{nivelOrden.map((k,i)=><div key={k} style={{flex:r.niveles.find(v=>v.k===k)?.n||.12,opacity:.4+i*.2}} title={k}/>)}</div><p className="tenue">{r.completas} encuestas nuevas terminadas · {r.conRespuestas} personas con alguna respuesta.</p></>}
 {slide===1&&<><p>La misma práctica, en la IA que cada quien tenga a mano.</p><Ranking items={r.herramientas} total={r.personas}/><p className="tenue">Las encuestas anteriores permitían elegir varias IA. No sumes sus barras como personas únicas.</p><Ranking items={r.dispositivos} total={r.personas}/>{r.herramientas.some(x=>x.k==='Todavía no tengo una cuenta')&&<div className="notice">Reserva tiempo de acceso al navegador. Si alguien no puede entrar, puede practicar en pareja.</div>}</>}
 {slide===2&&<><Horas h={r.horas}/><p>Tiempo semanal declarado en tareas repetitivas por {r.horas.n} personas. Es una estimación por intervalos, no ahorro garantizado.</p>{r.horas.anteriores>0&&<p className="tenue">{r.horas.anteriores} respuestas anteriores tienen intervalos distintos y quedan fuera de esta suma.</p>}<h3>¿Para qué nos gustaría recuperar parte de ese tiempo?</h3><div className="word-cloud">{nube.map(([w,n])=><span key={w} style={{fontSize:Math.min(2.5,1+n*.2)+'rem'}} title={n+' personas'}>{w}</span>)}</div><p className="tenue">Palabras de {suenos.length} cierres autorizados para mostrar. Cada palabra cuenta una vez por persona. {suenos.length?'':'Los primeros sueños aparecerán aquí.'}</p></>}
 {slide===3&&<><p>Lo que nos gustaría dejar de hacer a mano. Las confesiones se muestran sin nombre ni firma.</p><div className="task-grid">{publicos.filter(p=>p.tarea).map((p,i)=><article className="task" key={i}><h3>“{p.tarea}”</h3></article>)}</div>{!publicos.some(p=>p.tarea)&&<p className="empty">Todavía no hay confesiones autorizadas para mostrar.</p>}</>}
 {slide===4&&<><p>De dónde sale el trabajo y qué resultado necesita. Cada ruta cuenta personas que describieron una tarea y ambos extremos.</p><div className="flow-list">{r.patrones.map((p,i)=><div className="flow-row" key={p.id}><span>{p.origen}</span><span className="flow-arrow" aria-label="hacia">→</span><span>{p.destino}</span><strong>{p.n} {p.n===1?'persona':'personas'}{i===0?' · ruta más frecuente':''}</strong></div>)}</div>{!r.patrones.length&&<p className="empty">El mapa aparece al responder origen y destino.</p>}<p className="tenue">{r.tareas.filter(t=>!t.origen||!t.destino).length} tareas aún sin una ruta completa.</p></>}
 {slide===5&&<><h3>Esto es lo que queremos practicar hoy</h3><p>Tu voto pesa. Elegimos tres capacidades diferentes y buscamos ayudar al mayor número de personas.</p><Ranking items={r.votos} total={r.votos.reduce((n,v)=>n+v.n,0)}/><div className="reason"><strong>Selección provisional por cobertura y votos</strong><p>{r.seleccion.nota}</p>{r.seleccion.patrones.map(p=><p key={p.id}>{p.k} · {p.n} casos · {p.superpoder}</p>)}</div><button className="btn" onClick={onGenerar} disabled={ocupado||!r.tareas.length}>Generar los tres ejercicios de esta sala →</button></>}
 {slide===6&&<>{freno?<><div className="insight"><span className="eyebrow">{empates.length>1?'FRENOS EMPATADOS':'EL FRENO MÁS MENCIONADO'}</span><h2>{empates.map(x=>x.k).join(' · ')}</h2><p>{freno.n} personas por opción</p></div>{empates.map(f=><div className="reason" key={f.k}><strong>{f.k}</strong><p>{RESPUESTAS_FRENO[f.k]||'Partiremos de un ejemplo pequeño, con datos ficticios, y comprobaremos el resultado juntos.'}</p></div>)}<p className="tenue">Guion sugerido para Liliana: reconocer la preocupación y demostrar una práctica concreta.</p></>:<p className="empty">Aún no hay respuestas.</p>}</>}
 </div><div className="story-controls"><button className="btn fantasma" disabled={slide===0} onClick={()=>setSlide(slide-1)}>← Anterior</button><span>{slide+1} de 7</span><button className="btn fantasma" disabled={slide===6} onClick={()=>setSlide(slide+1)}>Siguiente →</button></div></section>
}
